#!/usr/bin/env python3
"""Export the slicer's pigment-mix polynomial into ``scad_fullspectrum/_pigment_model.py``.

The slicers (OrcaSlicer, BambuStudio, Snapmaker Orca) blend two filaments with a
degree-4 polynomial that approximates the Mixbox pigment model.  The coefficients
live in ``FilamentMixerModel.hpp`` (MIT, Copyright (c) 2026 Justin Hayes); this
script converts that header into a Python table so the tool can predict the same
swatch the slicer shows.

    tools/export_pigment_model.py path/to/FilamentMixerModel.hpp
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HEADER = '''"""Degree-4 pigment-mix polynomial used by the slicers (generated file).

Source: FilamentMixerModel.hpp - see THIRD_PARTY_NOTICES.md.
Copyright (c) 2026 Justin Hayes, MIT licence.  Generated by
tools/export_pigment_model.py; do not edit by hand.
"""

from __future__ import annotations

N_FEATURES = 330
N_INPUTS = 7

# Monomial exponents, in the order the coefficients are stored.
POWERS: tuple[tuple[int, ...], ...] = (
'''

FOOTER = '''
)

COEF: tuple[tuple[float, float, float], ...] = (
'''

INTERCEPT = '''
)

INTERCEPT: tuple[float, float, float] = (
'''


def parse(path: Path) -> tuple[list[tuple[int, ...]], list[tuple[float, float, float]], tuple[float, float, float]]:
    text = path.read_text()
    powers_block = text.split("static const int POWERS[330][7] = {", 1)[1].split("};", 1)[0]
    coef_block = text.split("static const double COEF[330][3] = {", 1)[1].split("};", 1)[0]
    intercept_block = text.split("static const double INTERCEPT[3] = {", 1)[1].split("};", 1)[0]

    powers = [
        tuple(int(value) for value in re.findall(r"-?\d+", row))
        for row in re.findall(r"\{([^}]*)\}", powers_block)
    ]
    coefs = [
        tuple(float(value) for value in re.findall(r"[-+0-9.eE]+", row))
        for row in re.findall(r"\{([^}]*)\}", coef_block)
    ]
    intercept = tuple(float(value) for value in re.findall(r"[-+0-9.eE]+", intercept_block))

    if len(powers) != 330 or len(coefs) != 330 or len(intercept) != 3:
        raise SystemExit(f"unexpected table sizes: {len(powers)}, {len(coefs)}, {len(intercept)}")
    if any(len(row) != 7 for row in powers) or any(len(row) != 3 for row in coefs):
        raise SystemExit("unexpected row widths")
    return powers, coefs, intercept


def render(powers, coefs, intercept) -> str:
    out = [HEADER]
    for row in powers:
        out.append("    (" + ", ".join(str(value) for value in row) + "),\n")
    out.append(FOOTER)
    for row in coefs:
        out.append("    (" + ", ".join(f"{value!r}" for value in row) + "),\n")
    out.append(INTERCEPT)
    out.append("    " + ", ".join(f"{value!r}" for value in intercept) + ",\n)\n")
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if len(args) != 1:
        print(__doc__)
        return 2
    powers, coefs, intercept = parse(Path(args[0]))
    target = Path(__file__).resolve().parents[1] / "scad_fullspectrum" / "_pigment_model.py"
    target.write_text(render(powers, coefs, intercept))
    print(f"wrote {target} ({target.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
